# Generated by Django 4.2.3 on 2025-05-03 17:31

import core.utils
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('brand', models.CharField(max_length=50, verbose_name='Brand')),
                ('model', models.PositiveSmallIntegerField(verbose_name='Model')),
                ('year', models.PositiveIntegerField(verbose_name='Reg. Year')),
                ('engine_capacity', models.CharField(max_length=20, verbose_name='Engine Capacity (cc)')),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid')], max_length=20, verbose_name='Fuel Type')),
                ('mileage', models.CharField(max_length=20, verbose_name='Mileage')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price (BDT)')),
                ('transmission', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATIC', 'Automatic')], max_length=20, verbose_name='Transmission')),
                ('drive_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Drive Type/Train')),
                ('wheel_base', models.CharField(max_length=20, verbose_name='Wheel')),
                ('color', models.CharField(blank=True, max_length=30, null=True, verbose_name='Color/Exterior')),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('USED', 'Used')], max_length=10, verbose_name='Condition')),
                ('registered', models.BooleanField(default=False, verbose_name='Registered')),
                ('body_style', models.CharField(blank=True, max_length=50, null=True, verbose_name='Body Style')),
                ('feature_image', models.FileField(help_text='jpg, jpeg, png', upload_to=core.utils.images_path_dir, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Image')),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('PUBLISHED', 'PUBLISHED'), ('UNPUBLISHED', 'UNPUBLISHED'), ('ARCHIVED', 'ARCHIVED')], default='PUBLISHED', max_length=12, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventories',
                'db_table': 'tbl_inventories',
            },
        ),
        migrations.CreateModel(
            name='InventoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=100, null=True, verbose_name='Caption')),
                ('image', models.FileField(help_text='jpg, jpeg, png', upload_to=core.utils.images_path_dir, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Image')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_images', to='inventory.inventory', verbose_name='Inventory')),
            ],
            options={
                'verbose_name': 'Inventory Image',
                'verbose_name_plural': 'Inventory Images',
                'db_table': 'tbl_inventory_images',
            },
        ),
    ]
