# Generated by Django 4.2.3 on 2025-05-04 13:46

import core.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='engine_capacity',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Engine Capacity (cc)'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='feature_image',
            field=models.FileField(blank=True, help_text='jpg, jpeg, png', null=True, upload_to=core.utils.images_path_dir, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='mileage',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mileage'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='wheel_base',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Wheel'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Reg. Year'),
        ),
    ]
