# Generated by Django 4.2.3 on 2025-05-04 14:46

import core.utils
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_engine_capacity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=100, verbose_name='Body Style')),
            ],
            options={
                'verbose_name': 'Body Style',
                'verbose_name_plural': 'Body Styles',
                'db_table': 'tbl_body_style',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Heading')),
                ('image', models.FileField(help_text='jpg, jpeg, png', upload_to=core.utils.images_path_dir, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Car Brand',
                'verbose_name_plural': 'Car Brands',
                'db_table': 'tbl_brand',
            },
        ),
        migrations.AlterField(
            model_name='inventory',
            name='registered',
            field=models.BooleanField(default=False, verbose_name='Availability'),
        ),
        migrations.CreateModel(
            name='ModelGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_generations_brand', to='inventory.brand', verbose_name='Brand')),
            ],
            options={
                'verbose_name': 'Model Generation',
                'verbose_name_plural': 'Model Generations',
                'db_table': 'tbl_model_generations',
            },
        ),
        migrations.AlterField(
            model_name='inventory',
            name='body_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories_body_style', to='inventory.bodystyle', verbose_name='Body Style'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories_brand', to='inventory.brand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories_model', to='inventory.modelgeneration', verbose_name='Model Generation'),
        ),
    ]
