# Generated by Django 4.2.3 on 2025-05-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_bodystyle_brand_alter_inventory_registered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodystyle',
            name='status',
            field=models.CharField(choices=[('PUBLISHED', 'PUBLISHED'), ('UNPUBLISHED', 'UNPUBLISHED'), ('ARCHIVED', 'ARCHIVED')], default='PUBLISHED', max_length=12, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='brand',
            name='status',
            field=models.CharField(choices=[('PUBLISHED', 'PUBLISHED'), ('UNPUBLISHED', 'UNPUBLISHED'), ('ARCHIVED', 'ARCHIVED')], default='PUBLISHED', max_length=12, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='modelgeneration',
            name='status',
            field=models.CharField(choices=[('PUBLISHED', 'PUBLISHED'), ('UNPUBLISHED', 'UNPUBLISHED'), ('ARCHIVED', 'ARCHIVED')], default='PUBLISHED', max_length=12, verbose_name='Status'),
        ),
    ]
