# Generated by Django 4.2.3 on 2025-05-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_bodystyle_status_brand_status_modelgeneration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='inventory_type',
            field=models.CharField(choices=[('LUXURY', 'LUXURY'), ('BUDGET_FRIENDLY', 'BUDGET_FRIENDLY')], default='BUDGET_FRIENDLY', max_length=20, verbose_name='Inventory Type'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Is Featured?'),
        ),
    ]
