# Generated by Django 4.2.3 on 2025-05-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventory_inventory_type_inventory_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='car_type',
            field=models.CharField(blank=True, choices=[('BRAND NEW', 'BRAND NEW'), ('PRE OWNED', 'PRE OWNED')], max_length=12, null=True, verbose_name='Car Type'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='youtube',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Youtube URL'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='condition',
            field=models.CharField(choices=[('NEW', 'NEW'), ('USED', 'USED')], max_length=10, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='fuel_type',
            field=models.CharField(choices=[('PETROL', 'PETROL'), ('DIESEL', 'DIESEL'), ('ELECTRIC', 'ELECTRIC'), ('HYBRID', 'HYBRID')], max_length=20, verbose_name='Fuel Type'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inventory_type',
            field=models.CharField(choices=[('LUXURY', 'LUXURY'), ('BUDGET FRIENDLY', 'BUDGET FRIENDLY')], default='BUDGET FRIENDLY', max_length=20, verbose_name='Inventory Type'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='transmission',
            field=models.CharField(choices=[('MANUAL', 'MANUAL'), ('AUTOMATIC', 'AUTOMATIC')], max_length=20, verbose_name='Transmission'),
        ),
    ]
