# Generated by Django 4.2.3 on 2025-07-22 19:12

import core.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventory_car_type_inventory_youtube_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=32, verbose_name='Email')),
                ('phone', models.CharField(max_length=18, verbose_name='Phone')),
            ],
            options={
                'verbose_name': 'Inventory Quote',
                'verbose_name_plural': 'Inventory Quote',
                'db_table': 'tbl_inventory_quote',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('image', models.FileField(help_text='jpg, jpeg, png', upload_to=core.utils.images_path_dir, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Image')),
                ('status', models.CharField(choices=[('PUBLISHED', 'PUBLISHED'), ('UNPUBLISHED', 'UNPUBLISHED'), ('ARCHIVED', 'ARCHIVED')], default='PUBLISHED', max_length=12, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'db_table': 'tbl_stocks',
            },
        ),
    ]
