# Generated by Django 4.2.3 on 2025-07-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventoryquote_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='fuel_type',
            field=models.CharField(choices=[('PETROL', 'PETROL'), ('DIESEL', 'DIESEL'), ('OCTANE', 'OCTANE'), ('ELECTRIC', 'ELECTRIC'), ('HYBRID', 'HYBRID'), ('CNG', 'CNG'), ('LPG', 'LPG'), ('ETHANOL', 'ETHANOL'), ('HYDROGEN', 'HYDROGEN'), ('BIO-DIESEL', 'BIO-DIESEL'), ('FLEX-FUEL', 'FLEX-FUEL'), ('OTHERS', 'OTHERS')], max_length=20, verbose_name='Fuel Type'),
        ),
    ]
