# Generated by Django 4.2.3 on 2025-08-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_inventory_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='registered',
            field=models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold'), ('Booked', 'Booked')], default='Available', max_length=12, verbose_name='Availability'),
        ),
    ]
