# Generated by Django 4.2.3 on 2025-08-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_inventory_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='car_type',
            field=models.CharField(blank=True, choices=[('RECOMMENDATION', 'RECOMMENDATION'), ('BRAND NEW', 'BRAND NEW'), ('PRE OWNED', 'PRE OWNED')], max_length=18, null=True, verbose_name='Car Type'),
        ),
    ]
