# Generated by Django 4.2.3 on 2025-08-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_inventory_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='car_type',
            field=models.CharField(blank=True, choices=[('RECONDITIONED', 'RECONDITIONED'), ('BRAND NEW', 'BRAND NEW'), ('PRE OWNED', 'PRE OWNED')], max_length=25, null=True, verbose_name='Car Type'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='fuel_type',
            field=models.CharField(choices=[('PETROL', 'PETROL'), ('DIESEL', 'DIESEL'), ('OCTANE', 'OCTANE'), ('ELECTRIC', 'ELECTRIC'), ('HYBRID', 'HYBRID'), ('CNG', 'CNG'), ('LPG', 'LPG'), ('ETHANOL', 'ETHANOL'), ('HYDROGEN', 'HYDROGEN'), ('BIO-DIESEL', 'BIO-DIESEL'), ('FLEX-FUEL', 'FLEX-FUEL'), ('PETROL+HYBRID', 'PETROL+HYBRID'), ('DIESEL+HYBRID', 'DIESEL+HYBRID'), ('OCTANE+HYBRID', 'OCTANE+HYBRID'), ('CNG+HYBRID', 'CNG+HYBRID'), ('LPG+HYBRID', 'LPG+HYBRID'), ('OTHERS', 'OTHERS')], max_length=20, verbose_name='Fuel Type'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Price (BDT)'),
        ),
    ]
