# Generated by Django 4.2.3 on 2025-08-28 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_inventory_car_type_alter_inventory_fuel_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryquote',
            options={'verbose_name': 'Inventory Get a Quote', 'verbose_name_plural': 'Inventory Get a Quote'},
        ),
    ]
