# Generated by Django 4.2.3 on 2025-08-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_inventoryquote_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='car_type',
            field=models.CharField(blank=True, choices=[('RECONDITIONED', 'RECONDITIONED'), ('BRAND_NEW', 'BRAND NEW'), ('PRE_OWNED', 'PRE OWNED')], max_length=25, null=True, verbose_name='Car Type'),
        ),
    ]
