# Generated by Django 4.2.3 on 2025-08-30 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_inventory_car_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryquote',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='inventory.inventory', verbose_name='Car'),
        ),
    ]
