# Generated by Django 4.2.3 on 2025-09-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_inventoryquote_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='slightly_negotiable',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=5, verbose_name='Is Slightly Negotiable?'),
        ),
    ]
