# Generated by Django 4.2.3 on 2025-05-03 17:31

import core.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Heading')),
                ('image', models.FileField(help_text='jpg, jpeg, png', upload_to=core.utils.images_path_dir, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Car Brand',
                'verbose_name_plural': 'Car Brands',
                'db_table': 'tbl_brand',
            },
        ),
        migrations.CreateModel(
            name='SellCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Your Name')),
                ('phone', models.CharField(max_length=18, verbose_name='Your Phone Number')),
                ('car_name', models.CharField(max_length=100, verbose_name='Car Name')),
                ('car_model', models.CharField(max_length=100, verbose_name='Car Model')),
                ('car_year', models.CharField(max_length=100, verbose_name='Car Year')),
                ('mileage', models.PositiveIntegerField(verbose_name='Mileage')),
                ('image', models.FileField(help_text='jpg, jpeg, png', upload_to=core.utils.images_path_dir, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Sell Your Car',
                'verbose_name_plural': 'Sell Your Cars',
                'db_table': 'tbl_sellcar',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100, verbose_name='Heading')),
                ('image', models.FileField(help_text='jpg, jpeg, png', upload_to=core.utils.images_path_dir, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Slider Image',
                'verbose_name_plural': 'Slider Images',
                'db_table': 'tbl_slider',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FACEBOOK', 'Facebook'), ('TWITTER', 'Twitter'), ('INSTAGRAM', 'Instagram'), ('YOUTUBE', 'Youtube')], max_length=10, verbose_name='Platform')),
                ('image', models.FileField(help_text='jpg, jpeg, png', upload_to=core.utils.images_path_dir, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Media',
                'db_table': 'tbl_socialmedia',
            },
        ),
    ]
