# Generated by Django 4.2.3 on 2025-05-05 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='image',
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='url',
            field=models.URLField(max_length=300, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
