# Generated by Django 4.2.3 on 2025-05-05 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_socialmedia_image_socialmedia_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='name',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='url',
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='facebook',
            field=models.URLField(max_length=300, verbose_name='Facebook'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='instagram',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='twitter',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='X'),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='youtube',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Youtube'),
        ),
    ]
