# Generated by Django 4.2.3 on 2025-05-15 05:48

import core.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_socialmedia_name_remove_socialmedia_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleTalkAboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('image', models.FileField(help_text='jpg, jpeg, png', upload_to=core.utils.images_path_dir, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Image')),
                ('url', models.URLField(blank=True, max_length=300, null=True, verbose_name='URL')),
                ('status', models.CharField(choices=[('PUBLISHED', 'PUBLISHED'), ('UNPUBLISHED', 'UNPUBLISHED'), ('ARCHIVED', 'ARCHIVED')], default='PUBLISHED', max_length=12, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'People Talk About Us',
                'verbose_name_plural': 'People Talk About Us',
                'db_table': 'tbl_people_talk',
            },
        ),
    ]
