# Generated by Django 4.2.3 on 2025-05-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_peopletalkaboutus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopletalkaboutus',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Title'),
        ),
    ]
