# Generated by Django 4.2.3 on 2025-05-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_peopletalkaboutus_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='peopletalkaboutus',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Is featured?'),
        ),
    ]
