# Generated by Django 4.2.3 on 2025-05-28 08:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_peopletalkaboutus_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='peopletalkaboutus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peopletalkaboutus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
