# Generated by Django 4.2.3 on 2025-07-22 19:41

import core.utils
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_peopletalkaboutus_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellYourCarImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(help_text='jpg, jpeg, png', upload_to=core.utils.images_path_dir, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Image')),
                ('sellcar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_images', to='home.sellcar', verbose_name='Sell Car')),
            ],
            options={
                'verbose_name': 'Inventory Image',
                'verbose_name_plural': 'Inventory Images',
                'db_table': 'tbl_sell_your_cars_images',
            },
        ),
    ]
