# Generated by Django 4.2.3 on 2025-07-23 21:52

import core.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_sellyourcarimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellcar',
            name='image',
            field=models.FileField(blank=True, help_text='jpg, jpeg, png', null=True, upload_to=core.utils.images_path_dir, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Image'),
        ),
    ]
