# Generated by Django 4.2.3 on 2025-07-31 18:33

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_sellcar_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Slider Video', 'verbose_name_plural': 'Slider Video'},
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.FileField(upload_to=core.utils.images_path_dir, verbose_name='Video'),
        ),
        migrations.AlterModelTable(
            name='slider',
            table='tbl_video',
        ),
    ]
