# Generated by Django 4.2.3 on 2025-08-11 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_slider_options_alter_slider_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellcar',
            name='image',
        ),
    ]
