# Generated by Django 4.2.3 on 2025-08-28 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_subscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peopletalkaboutus',
            options={'verbose_name': 'BEG across socials', 'verbose_name_plural': 'BEG across socials'},
        ),
        migrations.AlterModelOptions(
            name='sellcar',
            options={'verbose_name': 'Ready to sell your car?', 'verbose_name_plural': 'Ready to sell your car?'},
        ),
        migrations.AlterModelOptions(
            name='sellyourcarimages',
            options={'verbose_name': 'Ready to sell your car? Image', 'verbose_name_plural': 'Ready to sell your car? Images'},
        ),
    ]
