# Generated by Django 4.2.3 on 2025-09-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_peopletalkaboutus_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellcar',
            name='offered_price',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Offered Price'),
        ),
    ]
