# Generated by Django 4.2.3 on 2025-10-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_sellcar_offered_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Phone number')),
                ('status', models.CharField(choices=[('PUBLISHED', 'PUBLISHED'), ('UNPUBLISHED', 'UNPUBLISHED'), ('ARCHIVED', 'ARCHIVED')], default='PUBLISHED', max_length=12, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Sales representative',
                'verbose_name_plural': 'Sales representatives',
                'db_table': 'tbl_sales_representative',
                'ordering': ('name',),
            },
        ),
    ]
