# Generated by Django 4.2.3 on 2025-10-23 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_salesrepresentative'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesrepresentative',
            options={'ordering': ('name',), 'verbose_name': 'Sales Representative', 'verbose_name_plural': 'Sales Representatives'},
        ),
    ]
