# Generated by Django 4.2.3 on 2025-10-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_salesrepresentative_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrepresentative',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Phone number'),
        ),
    ]
